name: Cocogitto major bump
on: 
  workflow_dispatch:
    inputs:
      type:
        description: 'Version to bump'
        required: true
        default: 'major'
        type: choice
        options: 
          - major
          - major-beta
          - major-rc
jobs:
  major:
    if : github.event.inputs.type == 'major'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump Major Version
        uses: cocogitto/cocogitto-action@v3
      - run: |
            cog bump --major
  major-beta:
    if : github.event.inputs.type == 'major-beta'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump Major Version with Beta Suffix
        uses: cocogitto/cocogitto-action@v3
      - run: |
          cog bump --major --pre "beta"
  major-rc:
    if : github.event.inputs.type == 'major-rc'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Buump Major Version with Release Candidate Suffix
        uses: cocogitto/cocogitto-action@v3
      - run: |
          cog bump --major --pre "rc"
