name: Cocogitto major bump
on: workflow_dispatch
jobs:
  bump-version:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
      - name: Bump Major Version
        run: |
          cog bump --major
